version: '2'
services:
  # scale this with docker-compose scale es=3
  #es:
  #  image: elasticsearch:2.3
  #  expose:
  #    - "9200"
  #    - "9300"
  #  environment:
  #    - TZ=Asia/Shanghai

  #elasticsearch configuration node, should not be scaled
  #config is under /usr/share/elasticsearch/config
  #data is under /usr/share/elasticsearch/data
  elasticsearch:
    image: elasticsearch:5.2.1
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - "9300"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/data/elasticsearch:/usr/share/elasticsearch/data
      - /opt/es_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml